#!/bin/bash


cd "$(dirname "$0")"

git reset --hard 
git config pull.rebase false
git pull origin 


git status

echo 
echo "------------------"
echo "Updating Completed"
echo "------------------"
echo 
